basic functionality is working

diff --git a/umpa b/umpa
--- a/umpa
+++ b/umpa
@@ -1,34 +1,33 @@
 #!/bin/bash
 
-PLAYLIST=${1}
-PHONE_GUESS="/run/user/${UID}/gvfs/mtp*/Card/Music"
+source ~/.umpa
 
-MPD_CONFIG="${HOME}/.mpd/mpd.conf"
-# by default we look for a personal mpd.conf
-if [ ! -f "${MPD_CONFIG}" ]; then
-  echo "no mpd.conf file found"
-  exit 1
-fi
-
-# now we get the music and playlist directories
-MUSIC_DIR=$(egrep '^[[:space:]]*music_directory' "${MPD_CONFIG}" | cut -f2 -d'"')
-PLAYLIST_DIR=$(egrep '^[[:space:]]*playlist_directory' "${MPD_CONFIG}" | cut -f2 -d'"')
-
-echo "${MUSIC_DIR} :: ${PLAYLIST_DIR}"
-
-# if we weren't provided a playlist we let the user know
-# what's available
-if [ -z "${PLAYLIST}" ]; then
-  echo "You must provide us a playlist name. Here are the ones available:"
-  ls "${PLAYLIST_DIR}" | sed 's/.m3u$//; s/^/* /'
- exit 1
-fi
-# if we weren't provided a playlist we let the user know
-# what's available
-if [ ! -f "${PLAYLIST_DIR}/${PLAYLIST}.m3u" ]; then
-  echo "Sorry, I could find a M3U playlist with the name \"${PLAYLIST}\" (${PLAYLIST}.m3u)"
-  exit 1
-fi
+while getopts "s:l:vcn" opt; do
+  case $opt in
+    s)
+      ACTION=sync
+      PLAYLIST=$OPTARG
+      ;;
+    l)
+      ACTION=list
+      LIST_SELECTION=$OPTARG
+      ;;
+    v)
+      VERBOSE=1
+      ;;
+    n)
+      DRY_RUN=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
 # now we go looking for a phone under a gvfs mount point
 # they should be under /var/run/${UID}/mtp*
@@ -41,26 +40,85 @@ if [[ ${PHONE_COUNT} -ne 1 ]]; then
 fi
 PHONE_MOUNT="$(readlink -f ${PHONE_GUESS})"
 
-echo "${PHONE_MOUNT}"
+if [ $VERBOSE ]; then
+  echo "Music directory   : ${MUSIC_DIR}"
+  echo "Playlist directory: ${PLAYLIST_DIR}"
+  echo "Phone Mount       : ${PHONE_MOUNT}"
+fi
 
-echo "copying music file:"
-IFS='
+case $ACTION in
+  "sync")
+    # if we weren't provided a playlist we let the user know
+    # what's available
+    if [ -z "${PLAYLIST}" ]; then
+      echo "You must provide us a playlist name. Here are the ones available:"
+      ls "${PLAYLIST_DIR}" | sed 's/.m3u$//; s/^/* /'
+     exit 1
+    fi
+    # if we weren't provided a playlist we let the user know
+    # what's available
+    if [ ! -f "${PLAYLIST_DIR}/${PLAYLIST}.m3u" ]; then
+      echo "no M3U playlist with the name \"${PLAYLIST}\" (${PLAYLIST}.m3u)"
+      exit 1
+    fi
+
+    if [ $DRY_RUN ]; then
+      echo "*** dry run only ***"
+    fi
+    echo "syncing music:"
+    IFS='
 '
-for x in $(cat "${PLAYLIST_DIR}/${PLAYLIST}.m3u"); do
-  d=$(dirname $x)
-  echo "  - ${x}"
-  # make the directory if needed
-  if [ ! -d ${PHONE_MOUNT}/${d} ]; then
-    echo "    making target directory"
-    gvfs-mkdir -p ${PHONE_MOUNT}/${d}
-  fi
-  # copy the file if it doesn't exist
-  if [ ! -f ${PHONE_MOUNT}/${x} ]; then
-    echo "    copying file"
-    gvfs-copy ${MUSIC_DIR}/${x} ${PHONE_MOUNT}/${x}
-  fi
-done
+    for x in $(cat "${PLAYLIST_DIR}/${PLAYLIST}.m3u"); do
+      d=$(dirname $x)
+      echo -n "- ${x}"
+      # make the directory if needed
+      if [ ! -d ${PHONE_MOUNT}/${d} ]; then
+        if [ $VERBOSE ]; then
+          echo -n " .. create dir"
+        fi
+        if [ ! $DRY_RUN ]; then
+          gvfs-mkdir -p ${PHONE_MOUNT}/${d}
+        fi
+      fi
+      # copy the file if it doesn't exist
+      if [ ! -f ${PHONE_MOUNT}/${x} ]; then
+        if [ $VERBOSE ]; then
+          echo -n " .. syncing"
+        fi
+        if [ ! $DRY_RUN ]; then
+          gvfs-copy ${MUSIC_DIR}/${x} ${PHONE_MOUNT}/${x}
+        fi
+      else
+        if [ $VERBOSE ]; then
+          echo -n " .. exists"
+        fi
+      fi
+      echo
+    done
 
-
-
-gvfs-copy "${PLAYLIST_DIR}/${PLAYLIST}.m3u" "${PHONE_MOUNT}/Playlists/"
+    if [ $VERBOSE ]; then
+      echo "syncing playlist file ${PLAYLIST}"
+    fi
+    if [ ! $DRY_RUN ]; then
+      gvfs-copy "${PLAYLIST_DIR}/${PLAYLIST}.m3u" "${PHONE_MOUNT}/Playlists/"
+    fi
+    ;;
+  "list")
+    case $LIST_SELECTION in
+      "songs")
+        echo "listing contents of phone"
+        cd "${PHONE_MOUNT}" && find * -not -path "Playlists/*" -type f 
+        ;;
+      "playlists")
+        echo "listing playsists on phone"
+        cd "${PHONE_MOUNT}/Playlists" && find * -type f
+        ;;
+    esac
+    ;;
+  "clean")
+    echo "clean not yet implemented"
+    ;;
+  *)
+    echo "unknown option"
+    ;;
+esac
